name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm run install:all
      - name: lint
        run: npm run lint:front-end
      - name: build
        run: npm run build
      - name: test front-end
        run: npm run test:front-end
      - name: test back-end
        run: npm run test