name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
      SECRET: ${{secrets.SECRET}}
      PORT: ${{secrets.PORT}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm install
      - name: lint
        run: npm run lint:front-end
      - name: build
        run: npm run build
      - name: test front-end
        run: npm run test:front-end
      - name: test back-end
        run: npm run test
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,''),'#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-own-ci-pipeline"
          heroku_email: "olli.takaanttila@gmail.com"
          healthcheck: "https://full-stack-open-pokedex-ot.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGODB_URI: ${{secrets.MONGODB_URI}}
          HD_SECRET: ${{secrets.SECRET}}
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,''),'#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
